version: '2'
services:
  web:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment: 
      - SECRET=NPH2xmMIKI78gsIZ/BPCCpy6u6MnLbFhT4Oj1S/zky0=
      - DATABASE_URL=mongodb://mongodb:27017/patients
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment: 
      - MONGO_DATA_DIR=/data/db
    volumes: 
      - ./data/db:/data/db
    command: mongod --smallfiles